# Generated by Django 3.1.1 on 2020-10-11 21:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201011_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.user')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\d+$')])),
                ('address', models.ManyToManyField(blank=True, to='registration.Address')),
            ],
        ),
    ]
