# Generated by Django 3.1.1 on 2020-10-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0007_auto_20201012_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_complete', models.DateTimeField()),
                ('origen', models.CharField(max_length=100)),
                ('discharge', models.CharField(max_length=100)),
                ('shipping_line', models.CharField(blank=True, max_length=100, null=True)),
                ('vessel_name', models.CharField(max_length=100)),
                ('etd', models.CharField(blank=True, max_length=100, null=True)),
                ('eta', models.CharField(blank=True, max_length=100, null=True)),
                ('seal', models.CharField(max_length=50)),
                ('container', models.CharField(max_length=20)),
                ('plant', models.CharField(max_length=50)),
                ('boxes', models.IntegerField(default=0)),
                ('net_weight', models.FloatField(default=0)),
                ('gross_weight', models.FloatField(default=0)),
                ('lot', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.client')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.inspector')),
            ],
        ),
        migrations.CreateModel(
            name='RowOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('product', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='WeightControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.FloatField()),
                ('carton', models.FloatField()),
                ('product', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps', to='orders.order')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.roworder')),
            ],
        ),
    ]
