# Generated by Django 3.1.1 on 2020-10-14 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 13, 46, 13, 997709)),
        ),
    ]
