# Generated by Django 3.1.1 on 2020-10-14 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201014_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
