# Generated by Django 3.1.1 on 2020-10-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201014_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('loading', 'loading'), ('cancel', 'cancel'), ('ready', 'ready')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
