# Generated by Django 3.1.1 on 2020-11-09 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201108_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
    ]
