# Generated by Django 3.1.1 on 2020-11-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201108_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
