# Generated by Django 3.1.1 on 2020-11-13 17:52

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201110_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty', models.ImageField(upload_to=orders.models.name_files_container)),
                ('matricula', models.ImageField(upload_to='products/')),
                ('ventilation', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='orders.order')),
            ],
        ),
    ]
