# Generated by Django 3.1.1 on 2020-11-13 18:01

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_containerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerorder',
            name='empty',
            field=models.ImageField(upload_to=orders.models.name_files_container),
        ),
        migrations.AlterField(
            model_name='containerorder',
            name='matricula',
            field=models.ImageField(upload_to=orders.models.name_files_container),
        ),
        migrations.AlterField(
            model_name='containerorder',
            name='ventilation',
            field=models.ImageField(blank=True, null=True, upload_to=orders.models.name_files_container),
        ),
    ]
