# Generated by Django 3.1.1 on 2020-11-15 04:57

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20201113_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='roworder',
            name='image',
            field=models.ImageField(default=1, upload_to=orders.models.name_files_row),
            preserve_default=False,
        ),
    ]
