# Generated by Django 3.1.1 on 2020-11-15 14:18

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_roworder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturecontrol',
            name='row',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ImageControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(choices=[('temperature', 'temperature'), ('weight', 'weight'), ('measure', 'measure')], max_length=15)),
                ('number', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to=orders.models.name_files_control)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.order')),
            ],
        ),
    ]
