# Generated by Django 3.1.1 on 2020-11-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20201115_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontrol',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roworder',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
