# Generated by Django 3.1.1 on 2020-12-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20201127_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganolepticControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('images', models.ManyToManyField(to='orders.ImageControl')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure', to='orders.order')),
            ],
        ),
    ]
