# Generated by Django 3.1.1 on 2020-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_organolepticcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturecontrol',
            name='images',
            field=models.ManyToManyField(to='orders.ImageControl'),
        ),
        migrations.AddField(
            model_name='weightcontrol',
            name='images',
            field=models.ManyToManyField(to='orders.ImageControl'),
        ),
    ]
